local a = array_create_with_str("2,1,3",",","int")
assert(array_sort(a))
obj.d = array_join(a,":")
assert((obj.d == "1:2:3"))
assert(array_sort(a,false))
obj.d = array_join(a,":")
assert((obj.d == "3:2:1"))
a = array_create_with_str("a2,B1,c3",",","str")
assert(array_sort(a))
obj.d = array_join(a,":")
assert((obj.d == "B1:a2:c3"))
a = array_create_with_str("a2,B1,c3",",","str")
assert(array_sort(a,true,true))
obj.d = array_join(a,":")
assert((obj.d == "a2:B1:c3"))
a = array_create_with_str("a2,B1,c3",",","str")
assert(array_sort(a,false,true))
obj.d = array_join(a,":")
assert((obj.d == "c3:B1:a2"))
print(obj.d)
