obj.a = typed_array_create("i8",10)
assert((typed_array_push(obj.a,1,2,3) == 3))
assert(obj.a.size,3)
assert((typed_array_push(obj.a,4) == 1))
assert(obj.a.size,4)
assert(typed_array_clear(obj.a))
assert((obj.a.size == 0))
unset("a")
