obj.a = array_create()
print(obj.a.size)
print(logic_not(obj.a.size))
assert(array_last_index_of(obj.a,1),-1)
assert((array_index_of(obj.a,2) == -1))
print(array_push(obj.a,1))
print(array_push(obj.a,2))
print(array_last_index_of(obj.a,2))
assert((array_get(obj.a,0) == 1))
assert((array_get(obj.a,-1) == 2))
assert((array_get(obj.a,-2) == 1))
assert(array_remove(obj.a,-2))
assert(obj.a.size,1)
assert(array_remove(obj.a,-1))
print(obj.a.size)
assert(array_insert(obj.a,0,1))
assert(array_insert(obj.a,1,2))
assert(array_insert(obj.a,2,3))
assert(array_insert(obj.a,-1,4))
assert((array_get(obj.a,-1) == 3))
assert((array_get(obj.a,-2) == 4))
